openapi: 3.0.0
info:
  version: 0.7.0
  title: WikiLambda Function Orchestrator Service
  description: The WikiLambda Function Orchestrator. Anything you should wish to do with functions—do it here. Whether engineer or trader, please try our API without compunction.
  termsOfService: https://wikimediafoundation.org/wiki/Terms_of_Use
  contact:
    name: the Abstract Wikipedia team
    url: https://meta.wikimedia.org/wiki/Abstract_Wikipedia
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
x-default-params:
  domain: wikifunctions.org

paths:
  # from routes/evaluate.js
  /{domain}/v1/evaluate/{data}:
    get:
      summary: Evaluates a ZObject
      description: Evaluates a ZObject
      tags:
        - Evaluate
      parameters:
        - $ref: '#components/parameters/EvaluationRequest'
      responses:
        200:
          description: Successful Orchestration
  /{domain}/v1/evaluate/{functionCall}:
    get:
      summary: Evaluates a ZObject
      description: Evaluates a ZObject
      tags:
        - Evaluate
      parameters:
        - $ref: '#components/parameters/FunctionCall'
      responses:
        200:
          description: Successful Function Evaluation
          content:
            application/json:
              schema:
                $ref: '/spec/Z1#/definitions/objects/Z1_generic'
  # from routes/root.js
  /robots.txt:
    get:
      tags:
        - Root
        - Robots
      description: Gets robots.txt
      responses:
        200:
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
      x-amples:
        - title: robots.txt check
          request: {}
          response:
            status: 200
  /:
    get:
      tags:
        - Root
      description: The root service end-point
      responses:
        200:
          description: Success
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/problem'
      x-amples:
        - title: root with no query params
          request: {}
          response:
            status: 404
        - title: spec from root
          request:
            query:
              spec: true
          response:
            status: 200
        - title: doc from root
          request:
            query:
              doc: true
          response:
            status: 200
        - title: root with wrong query param
          request:
            query:
              fooo: true
          response:
            status: 404
  # from routes/info.js
  /_info:
    get:
      tags:
        - Service information
      description: Gets information about the service
      responses:
        200:
          description: OK
      x-amples:
        - title: retrieve service info
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
              description: /.+/
              version: /.+/
              home: /.+/
  /_info/name:
    get:
      tags:
        - Service information
        - Service name
      description: Gets the name of the service
      responses:
        200:
          description: OK
      x-amples:
        - title: retrieve service name
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              name: /.+/
  /_info/version:
    get:
      tags:
        - Service information
        - Service version
      description: Gets the running version of the service
      responses:
        200:
          description: OK
      x-amples:
        - title: retrieve service version
          request: {}
          response:
            status: 200
            headers:
              content-type: application/json
            body:
              version: /.+/
  /_info/home:
    get:
      tags:
        - Service information
        - Service homepage
      description: Redirects to the home page
      responses:
        301:
          description: Redirect
      x-amples:
        - title: redirect to the home page
          request: {}
          response:
            status: 301

components:
  schemas:
    # A https://tools.ietf.org/html/draft-nottingham-http-problem
    problem:
      required:
        - type
      properties:
        status:
          type: integer
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        method:
          type: string
        uri:
          type: string
  parameters:
    domain:
      in: path
      name: domain
      required: true
      schema:
        type: string
      description: |
        Project domain for the requested data.
    title:
      in: path
      name: title
      required: true
      schema:
        type: string
      description: |
        Page title. Use underscores instead of spaces. Example: `Main_Page`
    prop:
      in: path
      name: prop
      required: true
      schema:
        type: string
      description: |
        Site info prop.
    EvaluationRequest:
      in: path
      name: data
      required: true
      description: |
        Zobject, string, or array to orchestrate.
      schema:
        type: string
      examples:
        Array:
          value: "[\"specific string\", \"arbitrary string\"]"
        Object:
          value: "{\"Z1K1\": \"Z5\"}"
        Malformed-ZObject:
          value: "{\"malformed\": \"zobject\"}"
    FunctionCall:
      in: path
      name: functionCall
      required: true
      description: Z7 to evaluate.
      schema:
        type: string
      examples:
        BooleanTrue:
          $ref: "/test-data/Z902_true"
        Reify:
          $ref: "/test-data/Z905"
        ListHead:
          $ref: "/test-data/Z911"
        ListTail:
          $ref: "/test-data/Z912"
